
CREATE DATABASE IF NOT EXISTS store;
USE store;


CREATE TABLE IF NOT EXISTS users(
    idUser INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    firstName VARCHAR(50) NOT NULL,
    lastName VARCHAR(50) NOT NULL,
    numberPhone INT NOT NULL,
    email VARCHAR(40) NOT NULL,
    password VARCHAR(255) NOT NULL,
    image MEDIUMBLOB NOT NULL,
    verifified BOOLEAN NOT NULL DEFAULT FALSE
);





CREATE TABLE IF NOT EXISTS products(
    idProduct INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(150) NOT NULL,
    description MEDIUMTEXT NOT NULL,
    price FLOAT NOT NULL,
    name VARCHAR(100) NOT NULL,
    model VARCHAR(45) NOT NULL,
    rating FLOAT NOT NULL DEFAULT 0,
    stock INT NOT NULL,
    creatAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    
);
CREATE TABLE IF NOT EXISTS images(
    idImage INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    image MEDIUMBLOB NOT NULL,
    fkproduct INT NOT NULL,
    FOREIGN KEY (fkproduct) REFERENCES products(idProduct)
);

CREATE TABLE IF NOT EXISTS games(
    idGame INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    edition VARCHAR(45) NOT NULL,
    plataform VARCHAR(35) NOT NULL,
    clasification MEDIUMTEXT NOT NULL,
    gender VARCHAR(45) NOT NULL,
    studio VARCHAR(45) NOT NULL,
    fkproduct INT NOT NULL,
    FOREIGN KEY (fkproduct) REFERENCES products(idProduct)
);
CREATE TABLE IF NOT EXISTS toys(
    idToys INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    color VARCHAR(45) NOT NULL,
    tamano VARCHAR(45) NOT NULL,
    mark VARCHAR(45) NOT NULL,
    material VARCHAR(45) NOT NULL,
    fkproduct INT NOT NULL,
    FOREIGN KEY (fkproduct) REFERENCES products(idProduct)
);
CREATE TABLE IF NOT EXISTS computers(
    idComputers INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    measuares VARCHAR(45) NOT NULL,
    color VARCHAR(45) NOT NULL,
    capacity MEDIUMTEXT NOT NULL,
    conectivity MEDIUMTEXT NOT NULL,
    mark VARCHAR(45) NOT NULL,
    fkproduct INT NOT NULL,
    FOREIGN KEY (fkproduct) REFERENCES products(idProduct)
);
